### ISSUE TITLE
RWARE with MAPPO training

### ISSUE THREAD

**Issue by miguel-arrf** [uoe-agents/epymarl#22]
Hi!

Whenever I try to run the MAPPO algorithm, executing:

```
python3 src/main.py --config=mappo --env-config=gymma with env_args.time_limit=500 env_args.key="rware:rware-tiny-2ag-v1"
```

I obtain the following error:

```
Traceback (most recent call last):
  File "/Users/miguelferreira/PycharmProjects/AASMA/venv/lib/python3.8/site-packages/sacred/experiment.py", line 312, in run_commandline
    return self.run(
  File "/Users/miguelferreira/PycharmProjects/AASMA/venv/lib/python3.8/site-packages/sacred/experiment.py", line 276, in run
    run()
  File "/Users/miguelferreira/PycharmProjects/AASMA/venv/lib/python3.8/site-packages/sacred/run.py", line 238, in __call__
    self.result = self.main_function(*args)
  File "/Users/miguelferreira/PycharmProjects/AASMA/venv/lib/python3.8/site-packages/sacred/config/captured_function.py", line 42, in captured_function
    result = wrapped(*args, **kwargs)
  File "src/main.py", line 36, in my_main
    run(_run, config, _log)
  File "/Users/miguelferreira/PycharmProjects/AASMA/epymarl/src/run.py", line 55, in run
    run_sequential(args=args, logger=logger)
  File "/Users/miguelferreira/PycharmProjects/AASMA/epymarl/src/run.py", line 127, in run_sequential
    learner = le_REGISTRY[args.learner](mac, buffer.scheme, logger, args)
  File "/Users/miguelferreira/PycharmProjects/AASMA/epymarl/src/learners/ppo_learner.py", line 37, in __init__
    if self.args.standardise_rewards:
AttributeError: 'types.SimpleNamespace' object has no attribute 'standardise_rewards'

During handling of the above exception, another exception occurred:
```

Does anyone have any tip on how to fix it?

Thanks in advance!

**Comment by miguel-arrf** [comment]
I've found the problem: in the **mappo.yaml** file, and regarding [this commit](https://github.com/uoe-agents/epymarl/commit/41dbf26a9144bfc1db2095c941c777eedeb63f93), the flag _standardise_rewards_ was changed to _standardise_returns_, but the **'_standardise_rewards: False_'** wan't set. 

I was able to use IPPO because in the ippo.yaml file, both flags were set!

**Comment by aowen87** [comment]
I'm seeing this same issue. Any idea when this fix will be merged?
